CREATE TABLE `Productos` (
	`Id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`IdCampesino` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`NombreProducto` VARCHAR(100) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	`Imagen` VARCHAR(1000) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	`PesoNeto` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Precio` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Cantidad` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `FK_Productos_Usuarios` (`IdCampesino`) USING BTREE,
	CONSTRAINT `FK_Productos_Usuarios` FOREIGN KEY (`IdCampesino`) REFERENCES `POOGrupo4`.`Usuarios` (`Id`) ON UPDATE RESTRICT ON DELETE RESTRICT
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=24
;
